hosts: all
become: true
  tasks:
  - name: 'Install python'
    apt:
      name: python3-pip
      state: latest
      update_cache: true
  - name: Install requirements
    apt: 
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - virtualenv
      - python3-setuptools
  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu bionic stable
      state: present
  - name: Update apt and install docker-ce
    apt: update_cache=yes name=docker-ce state=latest
  - name: Install Docker Module for Python
    pip:
      name: docker
  - name: 'Pulling Jenkins install repo'
    git:
      repo: 'https://github.com/LukeBenson/install-scripts'
      dest: ./
  - name: 'Install Jenkins'
    shell: ./install-scripts/jenkins-install.sh
